sudo: required
dist: trusty
language: cpp

compiler:
  - gcc

env:
  - SEASTAR=/opt/seastar

install:
  - ./seastar/install_dep_trusty.sh
  - ./seastar/install_dependencies.sh

script:
  - cd seastar; make
