sudo: required

services:
  - docker

env:
  - SEASTAR=/opt/seastar

install:

script:
    - docker run -v `pwd`/seastar/install_dependencies.sh:/root/install_dependencies.sh ubuntu:16.04 bash /root/install_dependencies.sh
